### ISSUE TITLE
Per-deck configuration

### ISSUE THREAD

**Issue by aleksejrs** [lovac42/NoFuzzWhatsoever#1]
So, the default average ease in the add-on is 245%. But the deck options UI has an Ease option, which I guess becomes useless with this add-on enabled?

**Comment by aleksejrs** [comment]
How about using the Ease from the deck options, and generating the list as a range of Ease±(0,029 of Ease), changing Ease by 0,061 of Ease. Make Ease configurable.

**Comment by lovac42** [comment]
Not the same "ease". Supermemo calls it "ease factor", Anki calls it "factor" or "ease" depending on the user. The "ease" in deck options are should be called "bonus" instead. THEY ARE NOT THE SAME THING THAT YOU ARE REFERRING TO.

**Comment by aleksejrs** [comment]
I am talking about "Starting ease" and probably "Easy bonus", then.

**Comment by lovac42** [comment]
Easy bonus is not the same thing and will not affect factor. But "starting ease" will affect new cards. I created a new version to account for starting ease, but it's harder to fudge the numbers when you account for deck config options. https://github.com/lovac42/NoFuzzWhatsoever/blob/conf/src/NoFuzzWhatsoever.py

Read the new readme as well.
